### ISSUE TITLE
Rename `canBeClosed` prop in `Modal.tsx` 

### ISSUE THREAD

**Issue by bilgeyucel** [Hipo/hipo-frontend-project-starter#17]
~This prop refers to the ability to close the modal without action. That's why it should be renamed as `canBeClosedWithoutAction`. 
Otherwise, it sounds like it can never be closed and this option is impossible.~

`canBeClosed` prop doesn't have any necessary functionality apart from `shouldCloseOnOverlayClick` and `shouldCloseOnEsc` props. It should be removed

**Comment by edizcelik** [comment]
I think we can remove that prop altogether and use `shouldCloseOnOverlayClick` and `shouldCloseOnEsc`. With the combination of these two, we would have the same functionality.

**Comment by bilgeyucel** [comment]
Correct. I will update the issue.
