### ISSUE TITLE
`npm run test` fails because of jest 

### ISSUE THREAD

**Issue by bilgeyucel** [Hipo/hipo-frontend-project-starter#39]
When I want to push a commit, after `npm run test` script, I get the following error. Is it me or is there a problem with jest? Maybe it is related to our configs?

<img width="720" alt="Ekran Resmi 2020-10-07 14 42 26" src="https://user-images.githubusercontent.com/25897116/95326489-5b5a3380-08ab-11eb-81e7-06eb87132307.png">

## To reproduce: 
* `node v12.18.4` and `"jest": "26.4.2"`
* For me, the last working version of jest is `25.5.4`. With the last major version update (`>=26.0.0`), I get the error above.
----
If you want to copy-paste the error ⬇️ 
```
> hipo-frontend-ts-boilerplate@0.0.0 test /Users/apple/Desktop/hipo-frontend-project-starter
> jest

● Unrecognized CLI Parameters:

  Following options were not recognized:
  ["run-in-band", "test-location-in-results"]

  CLI Options Documentation:
  https://jestjs.io/docs/en/cli.html

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hipo-frontend-ts-boilerplate@0.0.0 test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hipo-frontend-ts-boilerplate@0.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2020-10-07T11_41_22_456Z-debug.log
```

**Comment by bilgeyucel** [comment]
Related issue from jest: https://github.com/facebook/jest/issues/10014#issuecomment-660536693

**Comment by bilgeyucel** [comment]
The reason was my local language being Turkish. This problem is solved when I convert English to primary preferred language under `System Preferences > Language & Region`

**Comment by cbilgili** [comment]
Setting the locale as below also works.
```
"scripts": {
    "test": "LANG='en_US.UTF-8' jest"
  },
```
