### ISSUE TITLE
Should we wrap unit tests with `desribe`?

### ISSUE THREAD

**Issue by brkn** [Hipo/hipo-frontend-project-starter#4]
At [numberUtils.test.ts](https://github.com/Hipo/hipo-frontend-project-starter/blob/master/src/utils/number/numberUtils.test.ts), tests are not wrapped with a `describe`.

Also should we add tests for decimal numbers like: `3.14` and `3,14`?

**Comment by mucahit** [comment]
Added with https://github.com/Hipo/hipo-frontend-project-starter/pull/7
